/*
 * This file is auto-generated by scripts/syncCommandSchemas.js.
 * Do not edit this file manually.
 */

import type { JSONSchema } from '../types/jsonSchema';

export const GENERATED_COMMAND_SCHEMAS: Record<string, JSONSchema> = {
  applyPreset: {
    type: "object",
    properties: {
      presetId: {
        type: "string",
        maxLength: 256
      }
    },
    additionalProperties: false
  },
  generateDigest: {
    type: "object",
    properties: {
      selectedFiles: {
        type: "array",
        maxItems: 5000,
        items: {
          type: "string",
          minLength: 1,
          maxLength: 4096,
          pattern: "^[^<>:\"|?*\\\\$]+$"
        }
      },
      outputFormat: {
        type: "string",
        enum: [
          "markdown",
          "json",
          "text"
        ]
      },
      redactionOverride: {
        type: "boolean"
      }
    },
    additionalProperties: false,
    required: [
      "selectedFiles"
    ]
  },
  loadRemoteRepo: {
    type: "object",
    properties: {
      repoUrl: {
        type: "string",
        minLength: 1,
        maxLength: 2048,
        pattern: "^https://github\\.com/[\\w\\-.]+/[\\w\\-.]+(?:\\.git)?$"
      },
      ref: {
        type: "string",
        maxLength: 128,
        pattern: "^[\\w\\-./_]+$"
      },
      sparsePaths: {
        type: "array",
        maxItems: 200,
        items: {
          type: "string",
          minLength: 1,
          maxLength: 4096
        }
      }
    },
    additionalProperties: false,
    required: [
      "repoUrl"
    ]
  },
  toggleRedactionOverride: {
    type: "object",
    properties: {
      enabled: {
        type: "boolean"
      }
    },
    additionalProperties: true
  },
  updateSelection: {
    type: "object",
    properties: {
      filePath: {
        type: "string",
        minLength: 1,
        maxLength: 4096,
        pattern: "^[^<>:\"|?*\\\\$]+$"
      },
      selected: {
        type: "boolean"
      }
    },
    additionalProperties: false,
    required: [
      "filePath",
      "selected"
    ]
  }
} as const;
