#!/usr/bin/env node
/*
 * Follow instructions in copilot-instructions.md exactly.
 */

const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const projectRoot = path.join(__dirname, "..");
const sourcePath = path.join(projectRoot, "resources", "webview", "commandSchemas.js");
const outputPath = path.join(projectRoot, "src", "config", "generatedCommandSchemas.ts");

function loadSchemaDefinitions(filePath) {
  const rawSource = fs.readFileSync(filePath, "utf8");
  const transformedSource = rawSource.replace(
    /export\s+const\s+COMMAND_SCHEMA_DEFINITIONS\s*=\s*/u,
    "module.exports = "
  );

  const sandbox = {
    module: { exports: {} },
    exports: {}
  };

  vm.runInNewContext(transformedSource, sandbox, { filename: filePath });
  const definitions = sandbox.module.exports;
  if (!definitions || typeof definitions !== "object") {
    throw new Error("Failed to load command schema definitions");
  }
  return definitions;
}

function pickDefined(value, mapper) {
  return value === undefined ? undefined : mapper(value);
}

function compactObject(input) {
  return Object.fromEntries(
    Object.entries(input).filter(([, value]) => value !== undefined)
  );
}

function convertProperty(property, context) {
  const type = property?.type;
  switch (type) {
    case "string":
      return compactObject({
        type: "string",
        minLength: property.minLength,
        maxLength: property.maxLength,
        pattern: property.pattern
      });
    case "boolean":
      return { type: "boolean" };
    case "enum":
      return compactObject({
        type: "string",
        enum: Array.isArray(property.enum) ? property.enum : undefined
      });
    case "array": {
      const items = property.items ? convertProperty(property.items, `${context}[]`) : undefined;
      return compactObject({
        type: "array",
        maxItems: property.maxLength ?? property.maxItems,
        items
      });
    }
    case "object":
      return convertSchema(property, context);
    default:
      throw new Error(`Unsupported schema type "${String(type)}" at ${context}`);
  }
}

function convertSchema(schema, context) {
  if (!schema || schema.type !== "object") {
    throw new Error(`Schema at ${context} must be an object schema`);
  }

  const properties = {};
  const required = [];

  for (const [key, descriptor] of Object.entries(schema.properties ?? {})) {
    const childContext = `${context}.${key}`;
    properties[key] = convertProperty(descriptor, childContext);
    if (descriptor && descriptor.required) {
      required.push(key);
    }
  }

  const base = compactObject({
    type: "object",
    properties,
    additionalProperties: schema.allowUnknown === true ? true : false,
    required: required.length > 0 ? required : undefined
  });

  return base;
}

function buildHostSchemas(definitions) {
  const entries = Object.entries(definitions)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([command, schema]) => [command, convertSchema(schema, `payload.${command}`)]);
  return Object.fromEntries(entries);
}

function formatOutput(schemas) {
  const header = [
    "/*",
    " * This file is auto-generated by scripts/syncCommandSchemas.js.",
    " * Do not edit this file manually.",
    " */",
    "",
    "import type { JSONSchema } from '../types/jsonSchema';",
    "",
    "export const GENERATED_COMMAND_SCHEMAS: Record<string, JSONSchema> = "
  ].join("\n");

  const body = JSON.stringify(schemas, null, 2).replace(/"([A-Za-z0-9_]+)":/gu, "$1:");
  return `${header}${body} as const;\n`;
}

function writeSchemas(content, destination, checkOnly) {
  if (checkOnly) {
    if (!fs.existsSync(destination)) {
      console.error("Command schema check failed: generated file is missing.");
      process.exit(1);
    }
    const existing = fs.readFileSync(destination, "utf8");
    if (existing !== content) {
      console.error("Command schema check failed: run npm run sync-command-schemas.");
      process.exit(1);
    }
    console.log("Command schema check passed.");
    return;
  }

  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.writeFileSync(destination, content, "utf8");
  console.log(`Wrote ${path.relative(projectRoot, destination)}`);
}

(function main() {
  try {
    const args = process.argv.slice(2);
    const checkOnly = args.includes("--check");

    const definitions = loadSchemaDefinitions(sourcePath);
    const hostSchemas = buildHostSchemas(definitions);
    const output = formatOutput(hostSchemas);

    writeSchemas(output, outputPath, checkOnly);
  } catch (error) {
    console.error("Failed to sync command schemas:", error);
    process.exit(1);
  }
})();
