name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Node ${{ matrix.node-version }} / VS Code ${{ matrix.vscode-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        vscode-version: [1.74.0, 1.85.0, latest]
    env:
      VSCODE_VERSION: ${{ matrix.vscode-version }}
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration

      - name: Check bundle size
        run: npm run check-bundle-size

      - name: Validate webview assets
        run: npm run check-webview-assets

      - name: Check handlers coverage
        run: npm run check-handlers-coverage

      - name: Build extension
        run: npm run build

      - name: Ensure package output directory exists
        run: mkdir -p dist

      - name: Package VSIX
        run: npm run package

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node-version }}-${{ matrix.vscode-version }}
          path: |
            coverage/
            test-results/
